### ISSUE TITLE
Adding a new CPU definition

### ISSUE THREAD

**Issue by exodustx0** [DigicoolThings/HxD_DasmDataInspectorPlugin#1]
How would one go at doing a PR for adding a new CPU definition? I wrote one for the Sony SPC700 (the SNES console's audio CPU), and figured it might be useful to add it to the collection rather than have it lying around elsewhere. I'm assuming, of course, that you'd be willing to have such a PR in the first place.

It's mostly because of the limit of 8 DasmTypes that I'm wondering how you'd like to have it done.

**Comment by DigicoolThings** [comment]
Hi. It would be great to add another contributed CPU definition to the repository.  I'm not familiar with the SPC700 audio co-processor. But if it's SNES related, I imagine there could be quite a few interested in this CPU being added. 

The 8 DasmTypes "limit" is simply a limit on how many CPU's you can have activated simultaneously.  I imagine for most people, they would only have the few specific CPU's that they are currently interested in included in their DasmTypes INI setting.

So to add a new CPU definition, you'd need the new named .csv file and the added named section in the DasmDataInspectorPlugin.ini file, and the appropriate description and accreditation for adding to the READEME.md.

In terms of creating a PR, I can only suggest reviewing online help / tutorials.  If you don't really want to go to the trouble of creating your own repository etc, the other option would be to just attach your additions / changes here, along with your prefered description & accreditation.  I could then commit the required updates on your behalf.

Cheers,
Greg

**Comment by exodustx0** [comment]
I don't mind doing the PR myself, that's not what I wasn't sure about. Rather, I implied (should've been explicit, my bad) that if I add this to the INI config, and other new additions get added too in the future, once there's more than 8 DasmTypes the README needs to clearly state that the user _must_ edit the INI to only activate DasmTypes they find relevant. 

I'll do you the PR later today!

**Comment by DigicoolThings** [comment]
Apologies for the misunderstanding.  Yes, I do agree, once we have in excess of 8 DasmTypes available we'll need to update the Installation Instructions, to include the now required configuration of the users preferred DasmTypes string. This, instead of being just noted as an optional step, as is currently described.  In addition, a comment in the .ini file to summarise all the available DasmType names (once they exceed the allowed 8), would also be helpful.  

Thanks for your work on SPC700.  A nice addition.

Once I merge your changes, you should post a comment to the forum thread etc. (at mh-nexus.de), to notify others who may also be interested in the SPC700 disassembly addition.
